// server/api/deploy.post.ts
import { defineEventHandler, readBody } from 'h3'
import { redisPub } from '../utils/cluster' // Adjust path if necessary
import { randomUUID } from 'crypto'

/**
 * Handles Hot-Reload deployment from the UI.
 * Upgraded to bidirectional feedback: CP broadcasts the YAML and actively
 * waits for the DP's execution result (SUCCESS/FAILED) via a temporary Redis subscriber.
 */
export default defineEventHandler(async (event) => {
  const body = await readBody(event)
  
  if (!body || !body.yaml) {
    return { status: 400, message: 'YAML content is required for deployment.' }
  }

  const targetGroup = body.targetGroup || 'main'
  
  // 💡 Generate a unique identifier for this specific deployment transaction
  const deployId = randomUUID() 
  console.log(`[Zefio CP] Broadcasting Hot-Reload [${deployId}] to cluster group: [${targetGroup}]`)

  // 1. Construct the command payload, injecting the deployId
  const commandPayload = {
    type: "command",
    action: "hot-reload",
    targetGroup: targetGroup,
    deployId: deployId, // 💡 DP will echo this ID back in the status report
    payload: {
      yaml: body.yaml
    }
  }

  // 2. Create a dedicated transient subscriber to listen for the DP's response
  // We duplicate the publisher client to avoid blocking other global operations
  const subscriber = redisPub.duplicate()
  await subscriber.subscribe('zefio:deploy:status')

  // 3. Create an asynchronous wait loop with a strict timeout guardrail
  const waitForStatus = new Promise((resolve, reject) => {
    
    // Architect's Guardrail: 15-second timeout to prevent infinite blocking if DP is dead
    const timeout = setTimeout(() => {
      subscriber.unsubscribe('zefio:deploy:status').catch(() => {})
      subscriber.quit().catch(() => {})
      reject(new Error('Deployment timed out. No response from DP nodes within 15 seconds.'))
    }, 15000)

    subscriber.on('message', (channel, message) => {
      if (channel === 'zefio:deploy:status') {
        try {
          const statusData = JSON.parse(message)
          
          // 💡 Only react to the status report that matches our current deployment ID
          if (statusData.deployId === deployId) {
            clearTimeout(timeout)
            
            // Clean up the transient subscriber immediately to free resources
            subscriber.unsubscribe('zefio:deploy:status').catch(() => {})
            subscriber.quit().catch(() => {})

            if (statusData.status === 'SUCCESS') {
              resolve(statusData)
            } else {
              // Extract and throw the actual error message generated by the DP (e.g., "PayloadBuilder is mandatory...")
              reject(new Error(`DP Node [${statusData.nodeId}] Error: ${statusData.message}`))
            }
          }
        } catch (err) {
          console.error('[Zefio CP] Error parsing DP status message', err)
        }
      }
    })
  })

  try {
    // 4. Publish the deployment command to the DPs
    await redisPub.publish('zefio:command', JSON.stringify(commandPayload))

    // 5. Await the feedback loop resolution
    const result: any = await waitForStatus

    return { 
      status: 200, 
      message: `Deployment successful on node ${result.nodeId}.` 
    }
    
  } catch (error: any) {
    console.error('[Zefio CP] Redis Deployment failed:', error.message)
    
    // Safety cleanup in case of unforeseen publish errors
    subscriber.unsubscribe('zefio:deploy:status').catch(() => {})
    subscriber.quit().catch(() => {})

    // Send the detailed error back to the Vue UI so the user can see exactly why it failed
    return { 
      status: 500, 
      message: error.message 
    }
  }
})